[package]
name = "git-streak"
version = "0.0.0"
description = "An app that track's your git commit streak!"
authors = ["winterwolf365"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["tray-icon", "image-png"] }
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-single-instance = "2.0.0-beta.5"
tauri-plugin-autostart = "2.0.0-beta.4"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

sqlx = { version = "0.7.4", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.37.0", features = ["full"] }
chrono = "0.4.37"
rfd = "0.14.1"
notify-rust = "4.11.0"

